#pragma once

#include "resource.h"
#include "framework.h"

#define FILE_DEVICE_IOCTL 0x00008301
#define DRV05_BASE_CTL_FUNC 0x800
#define IOCTL_MY_NEITHER CTL_CODE( \
	FILE_DEVICE_IOCTL, DRV05_BASE_CTL_FUNC+0, METHOD_NEITHER, FILE_ANY_ACCESS \
)
#define IOCTL_MY_BUFFERED CTL_CODE( \
	FILE_DEVICE_IOCTL, DRV05_BASE_CTL_FUNC+1, METHOD_BUFFERED, FILE_ANY_ACCESS \
)
#define IOCTL_MY_INDIRECT CTL_CODE( \
	FILE_DEVICE_IOCTL, DRV05_BASE_CTL_FUNC+2, METHOD_IN_DIRECT, FILE_ANY_ACCESS \
)
#define IOCTL_MY_OUTDIRECT CTL_CODE( \
	FILE_DEVICE_IOCTL, DRV05_BASE_CTL_FUNC+3, METHOD_OUT_DIRECT, FILE_ANY_ACCESS \
)
#define IOCTL_UNK_NEITHER CTL_CODE( \
	FILE_DEVICE_IOCTL, DRV05_BASE_CTL_FUNC+4, METHOD_NEITHER, FILE_ANY_ACCESS \
)
#define IOCTL_UNK_BUFFERED CTL_CODE( \
	FILE_DEVICE_IOCTL, DRV05_BASE_CTL_FUNC+5, METHOD_BUFFERED, FILE_ANY_ACCESS \
)
#define IOCTL_UNK_INDIRECT CTL_CODE( \
	FILE_DEVICE_IOCTL, DRV05_BASE_CTL_FUNC+6, METHOD_IN_DIRECT, FILE_ANY_ACCESS \
)
#define IOCTL_UNK_OUTDIRECT CTL_CODE( \
	FILE_DEVICE_IOCTL, DRV05_BASE_CTL_FUNC+7, METHOD_OUT_DIRECT, FILE_ANY_ACCESS \
)

enum CCHBUF {
	CCHBUF_TINY   = 16,
	CCHBUF_SMALL  = 64,
	CCHBUF_MEDIUM = 256,
	CCHBUF_BIG    = 65536
};